### ISSUE TITLE
Onscreen keyboard

### ISSUE THREAD

**Issue by guyellis** [guyellis/learn#10]
Number keyboard is causing problems.

**Comment by guyellis** [comment]
@ellisande I want to run something by you.

When using this app the only input field is set to type of number. This is great on mobile devices as it pops up the number keypad for entry. I've noticed in my field testing with my kids that this still causes problems and I'm thinking that for those devices input needs to be completely controlled and limited to an onscreen keyboard.

So to do that I'm thinking of hiding the input field and replacing it with a div that updates as the user taps on keys on an onscreen keyboard. I would need to keep focus on the hidden div so that a user using a keyboard would still be able to enter numbers from there.

Another idea would be to switch the input methods based on device. For tablets and phones use the onscreen keyboard and for others use the input box. Also allow the user to switch between the two.

What do you think?

**Comment by Ellisande** [comment]
I would think show it on demand. Since its somewhat hard to figure out if there is a keyboard present based on device. Unless there is a web api for seeing if a keyboard is connected?

**Comment by guyellis** [comment]
Closing because this is now part of the new Math Drill page.
