### ISSUE TITLE
You tried to redirect to the same route you're currently on: "/"

### ISSUE THREAD

**Issue by guyellis** [guyellis/learn#205]
React router warning:

```
Warning: You tried to redirect to the same route you're currently on: "/"
```

**Comment by u-can-miracle** [comment]
Wrap them in `Switch`

`         <Switch>
         <Route exact={true} path='/' component={Home} />
         <Route path='/about' component={About} />
         <Route path='/info' component={Info} />
           <Redirect to='/' />
         </Switch>`

**Comment by guyellis** [comment]
@u-can-miracle thanks for the idea. Unfortunately that and a number of other permutations around that didn't work in this case.

**Comment by u-can-miracle** [comment]
Strange it works for me [here](https://github.com/u-can-miracle/boilerplate/blob/master/client/src/containers/Routes/Routes.js#L14)
Maybe you have one more `<Redirect />` in another place?
The idea is that you come to route "/" twice

**Comment by guyellis** [comment]
@u-can-miracle I did the same [here](https://github.com/guyellis/learn/blob/master/src/app.jsx#L17) - let me know if you can see anything wrong with what I did.

**Comment by guyellis** [comment]
@u-can-miracle If you search the repo using the search input on GitHub above you'll see that there's only a single Redirect.

**Comment by u-can-miracle** [comment]
I think the reason is that u use two routes with same path
`  <Route path="/" component={Menu} />
        <Route path="/" exact component={Home} />`

**Comment by guyellis** [comment]
@u-can-miracle I already tried that but no luck.

I believe that's a valid react-router 4 pattern. i.e. everything matches `/` if you don't use exact. That means that the menu component appears at the top of every page which is right.

**Comment by pengliheng** [comment]
but i have no idear, if i want to 
```jsx
<Redirect to='/chat'/>
```
how can i go to a url like "/chat"
if i use <Redirect to='/chat'/> to go to '/chat',
the browser will give me a warn like:
```
You tried to redirect to the same route you're currently on: "/chat"
```

**Comment by pengliheng** [comment]
### how can i go to a new url while i use react-router-dom
```
'/' => '/chat'
```
#### if i login with my userName and passWord
and i want url like
'/' => '/chat'
to go to the '/chat' page

**Comment by pengliheng** [comment]
i noly found the idear in this way
```jsx
<Redirect to='/chat'/>
```
it didn't warn me at last week
,but now it throw a warn 
You tried to redirect to the same route you're currently on: "/chat"
it really hurt my confident

**Comment by guyellis** [comment]
@pengliheng that sounds like the same issue that we are discussing here and have not found a solution to.

**Comment by jonjaques** [comment]
I ran into this because I have a page that has children, but if you come into `/parent` I want to automatically redirect to `/parent/child`. I was able to work around like so:

```jsx
// path="/parent"
function Parent({match, location}) {
  let shouldRedirect = match.url === location.pathname;
  return <div>
    {shouldRedirect && <Redirect to="/parent/child" />}
    <Switch>
      <Route path="/parent/child" component={Foo} />
      <Route path="/parent/step-child" component={Bar} />
    </Switch>
  </div>
}
```

**Comment by guyellis** [comment]
@jonjaques I like that idea as a workaround. I tried this:

```
function app(props) {
  const { match, location } = props;
  const allowRedirect = match.url !== location.pathname;
  return (
    <div>
      <Route path="/" component={Menu} />
      <Route path="/" exact component={Home} />
      <Route path="/math/drill" exact component={Drill} />
      <Route path="/math/score" exact component={Scoreboard} />
      {<Route path="/help" exact component={Help} />}
      {allowRedirect &&
        <Redirect to="/" />
      }
    </div>
  );
}

app.propTypes = {
  match: PropTypes.shape({
    url: PropTypes.string.isRequired,
  }).isRequired,
  location: PropTypes.shape({
    pathname: PropTypes.string.isRequired,
  }).isRequired,
};
```

I think that because this is the parent element it's not getting `match` and `location` as props from the `Router` so unfortunately that doesn't work.

Thanks for the idea though!

**Comment by arjitaM** [comment]
I am facing the same issue. I have route config file i.e route.js

const Root = ({ store }) => (
    <Provider store={store}>
        <BrowserRouter>
            <div>
                <Route path='/' component={ App }/>
            </div>
        </BrowserRouter>
    </Provider>
)

Now at App.js

class AppComp extends Component {
    render() {
        const {match} = this.props;
        let navClass = 'active';

        if(this.props.sideClass === "nav-ssh") {
            navClass = "active-ssh"; 
        }

        return (
            <div>
                <div className="container">
                    <div className="main">
                        <Route render={()=><Header sideNavClass={this.props.sideNavClass} />} />
                        <Route render={()=><SideNav navActiveClass={navClass} currentLocation={this.props.location.pathname} />}/>
                        <Redirect to="/home/dashboard" />s
                    </div>
                </div>
            </div>
        );
    }
}

I want to load app always so put it in the highest level and header and sidenav should also gets loaded always so they are inside app.

For any unknown path and for first time load I redirected to /home/dashboard

I understand it must be coming to / twice so this warning.

How can I configure my router to achieve the same and resolve the warning.

**Comment by guyellis** [comment]
@arjitaM - that's what we're trying to figure out.

**Comment by damianobarbati** [comment]
@guyellis did you understand why this message?
```
<Route exact={true} path={'/'} render={() => <Redirect to={'/list/user'} />} />
<Route exact={true} path={'/list/user'} component={UserList} />
<Route exact={true} path={'/item/user/:id?'} component={UserItem} />
```
I get the following after the redirect:
```
Warning: You tried to redirect to the same route you're currently on: "/list/user"
```

**Comment by guyellis** [comment]
@damianobarbati I have not solved this yet.

**Comment by pabechevb** [comment]
I solved it by leaving the redirect at the bottom:
`		<Switch>
			<Route exact path="/issues" component={IssueList} />
			<Route exact path="/issues/:id" component={IssueEdit} />
			<Redirect from="/" to="/issues" />
			<Route exact path="*" component={NoMatch} />
		</Switch>`

**Comment by pabechevb** [comment]
I solved it by leaving the redirect at the bottom:
`		<Switch>`
`			<Route exact path="/issues" component={IssueList} />`
`			<Route exact path="/issues/:id" component={IssueEdit} />`
`			<Redirect from="/" to="/issues" />`
`			<Route exact path="*" component={NoMatch} />`
`		</Switch>`

**Comment by guyellis** [comment]
@pabechevb do you have time to clone this repo and try that? I've just tried doing that and I'm still getting that error on this repo. Thanks.

To see the error:

1. Clone this repo
2. `npm i`
3. `npm start`
4. Go to http://127.0.0.1:8888/ in your browser and see the error in the console window.

**Comment by pabechevb** [comment]
@guyellis I was able to resolve it for your project as follows:
`<Route path="/" component={Menu} />`
`	  <Route path="/math/drill" exact component={Drill} />`
`      <Route path="/math/score" exact component={Scoreboard} />`
`      <Route path="/help" exact component={Help} />`
`	  <Switch>`
`      <Route path="/" exact component={Home} />`
`      <Redirect to="/" />`
`	  </Switch>`
Also note that on every recompile, I'm getting an out of memory error, that's something you may want to check.

**Comment by guyellis** [comment]
@pabechevb none of the routes actually work with that change. Try click on the buttons on the web page after you've made that change and you'll see that yes, the error has gone but that the routing is also 100% broken.

Can you paste the out-of-memory output you're seeing? I'm not seeing that. And by compile are you talking about the output from `npm start` when you make a change to the code?

**Comment by pabechevb** [comment]
@guyellis You're right, you hadto include all the other routes:
`      <Route path="/" component={Menu} />`
`	  <Switch>`
`	  <Route path="/" exact component={Home} />`
`	  <Route path="/math/drill" exact component={Drill} />`
`      <Route path="/math/score" exact component={Scoreboard} />`
`      <Route path="/help" exact component={Help} />`
`      <Redirect to="/" />`
`	  </Switch>`
And I did not get the OutOfMemory error anymore, by recompile I refer to the output from `npm start` when you make a change to the code.

**Comment by guyellis** [comment]
Nice @pabechevb - I believe that fixes it.

Would you like to do a PR for that fix so that you get credit for fixing it? If not I can do it but wanted to make sure you are recognized for being awesome!

If you do decide to do a PR then when you make the commit include `fixes #205` in the comment and then when the PR is merged it will automatically tag and close this issue.

Let me know if you won't PR and I'll do the commit/fix/close. Thanks.

**Comment by mhebrard** [comment]
I get this warning today (react-router-dom: "^4.3.1")
Elements needed to avoid the warning are:
* encapsulate the routes in a ```<Switch>``` 
* move the ```<Redirect>``` after the ```<Route>```

```
render() {
    const {bool, match} = this.props;
    const {path} = match;
    let sub = <Redirect to={`${path}/first`}/>;
    if (bool === true) {
      sub = <Redirect push to={`${path}/second`}/>;
    }
    return (
      <Switch>
        <Route path=`${path}/form` component={First}/>
        <Route path=`${path}/results` component={Second}/>
        {sub}
      </Switch>
    );
}
```

**Comment by mhebrard** [comment]
I get the same warning 

```
render() {
    const {formIsValid, match} = this.props;
    const {path} = match;
    let redirect = <Redirect push to={`${path}/form`}/>;
    if (formIsValid === true) {
      redirect = <Redirect push to={`${path}/results`}/>;
    }
    console.log(redirect.props.to);
    return (
      <div>
        <Route path={`${path}/form`} component={GuideForm}/>
        <Route path={`${path}/results`} component={GuideResults}/>
        {redirect}
      </div>
    );
  }
```

**Comment by AndoniAditazz** [comment]
@mhebrard pass `exact` prop to Route component

**Comment by mhebrard** [comment]
Well The warning is trigger because the module that manage the redirection is still mounted on the page after redirection
```
/branch
/branch/form
/branch/result
```
one solution would be to do "independent" routes. Then when you display the form, branch is not mount so the redirection is not trigger

```
/branch /* manage redirection */
/form 
/results
```

I choose to keep the "hierarchical" routes but test the current route (as suggested in the comments above)

```
/branch /* Manage redirection + display form */
/branch/result

render() {
    const {formIsValid, location, match} = this.props;
    const {path} = match;
    return (
      <div>
        <Route exact path={path} component={BranchForm}/>
        <Route path={`${path}/results`} component={BranchResults}/>
        { /* Redirect to results when form is valid */
          /* Check location to redirect only when needed */
          formIsValid === true && path === location.pathname &&
          <Redirect push to={`${path}/results`}/>
        }
      </div>
    );
  }
```

**Comment by matt-macleod** [comment]
> I get the same warning
> 
> ```
> render() {
>     const {formIsValid, match} = this.props;
>     const {path} = match;
>     let redirect = <Redirect push to={`${path}/form`}/>;
>     if (formIsValid === true) {
>       redirect = <Redirect push to={`${path}/results`}/>;
>     }
>     console.log(redirect.props.to);
>     return (
>       <div>
>         <Route path={`${path}/form`} component={GuideForm}/>
>         <Route path={`${path}/results`} component={GuideResults}/>
>         {redirect}
>       </div>
>     );
>   }
> ```

Try wrapping in a `<Switch />` component and making the `<Route />` component's a direct child of the Switch.

Ensure the `div` that currently wraps the Routes wrap the Switch instead.

**Comment by lfernando-silva** [comment]
I don't know if it's really a good approach, but this solve my problem.

```js
class App extends Component {
    componentDidMount(){
        const { location, history } = this.props;
        console.log(this.props);
        const denyRedirect = ['/login','/directory'].filter(p => p === location.pathname)[0];

        if(!denyRedirect){
            history.push('/directory');
        }
    }

    render() {
        return (
            <div className="App" style={{padding: '1%', paddingLeft: '2%', paddingRight: '2%'}}>
                <Switch>
                    <Fragment>
                        <MainNavigation/>
                        <Route exact path="/login" component={withRouter(Login)}/>
                        <ProtectedRoute exact path='/directory' component={withRouter(Directory)}/>
                       {/* {!denyRedirect && <Route path={'*'} component={withRouter(Directory)} />}*/}
                    </Fragment>
                </Switch>
            </div>
        );
    }
}
```

**Comment by BenGedi** [comment]
just leave the "/" to the last chance.
for me helped to move "/" to the bottom of the <switch>

from:
```
<Switch>
    <Route path='/' component={Payment} />
     <Route exact path='/thanks' component={Thanks} />
</Switch>
```

to:
```
<Switch>
    <Route exact path='/thanks' component={Thanks} />
    <Route path='/' component={Payment} />
</Switch>
```

**Comment by erosenberg** [comment]
Here is my workaround...
First I created some helper functions in another utils file I created called `history.js`.

```
export const isIndexRoute = (url, path = window.location.pathname) => url === path;

export const endsInSlash = path => path.charAt(path.length - 1) === '/';

export const formatRedirectUrl = (path, subroute) => {
  let output = path;
  if (!endsInSlash(path)) {
    output += '/';
  }
  if (subroute) {
    output += subroute;
  }
  return output;
};
```
Then, in my file that contains routes, I put this `Redirect` at the end of the list.

```
    import { formatRedirectUrl, isIndexRoute } from 'utils/history';

    .........
    render() {
       const defaultRoute = 'pulse';
       const shouldRedirect = isIndexRoute(match.url);

       return (
          .........
          {shouldRedirect &&
              <Redirect
                from={match.url}
                to={`${formatRedirectUrl(match.url, defaultRoute)}`}
              />
            }
       )
    }

```

**Comment by SerhiiBilyk** [comment]
I had also same issue.
Next code is working:
```javascript
  <Router>
          <Switch>
            <Route
              exact
              path="/partner"
              render={props => <PartnerContainer {...props} {...this.props} />}
            />
            <Route
              exact
              path="/manager"
              render={props => <ManagerContainer {...props} {...this.props} />}
            />
            {check && <Redirect from="/" to={`/${role}`} />}
          </Switch>
 </Router>
```
All what you need to do is to wrap your Route's components in Switch.
Hope it will help somebody

**Comment by sudippurkayastha** [comment]
If i try to redirect to "/" on action of a click of a button, i get the error **_You tried to redirect to the same route you're currently on: "/"_**

I use the following to redirect to route, 
**<Redirect to='/'** 


Route config
-------------------------
                                <Switch>                                    
                                    <Route exact path='/sb/new/:dept' component={NewSb}/>
                                    <Route exact path='/:dept/sb/:sb' component={SbDetails}/>
                                    <Route exact push path='/:dept/:sbstatus' component={props=> <Dashboard {...props} />}/>
                                    <Route push path="*" render={() => (<Redirect to={'/' + division + '/-1'} />)} />
                                </Switch>

**Comment by shabbir-ahmed** [comment]
I have code like that 

```
<Switch>
        <Redirect from="*" to={{
               pathname: `/search`,
               state: { term: this.state.term}
        }} />
</Switch>
```

but showing 

> Warning: You tried to redirect to the same route you're currently on: "/search"

how I can solve this?
