### ISSUE TITLE
React Route always taking to parent component

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [guyellis/learn#379]
export default (

  <Route path="/" component={App}>
  <IndexRoute component={App} />
    <Route path="/register" component={Register} />
    <Route path="/thankyou" component={RegisterSuccess} />
    <Route path="/login" component={UserLogin} />
  </Route>
);

if i browser for localhost://8080/**register** it is creating the first component{App} of parent route '/'

creating the first component which is the parent Route.

**Comment by guyellis** [comment]
@jeevankumarkanuganti can you give me a better example of what you're seeing or describe the steps required to reproduce this?

**Comment by jeevankumarkanuganti** [comment]
@guyellis  , Thanks for responding .
This issue got resolved . There is small syntax issue. Found it !!!
