### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by djKooks** [guyellis/learn#452]
Hello
This project looks like having good concept. I'm wondering if there is some kind of roadmap or plan of how to extend this project. It would be good to open it for the people who wants to get involved.

Thanks.

**Comment by guyellis** [comment]
@djKooks it's definitely open for anybody who wants to get involved. I don't have a roadmap but I'm total open to suggestions, help and PRs.

**Comment by djKooks** [comment]
Okay, thanks!
