### ISSUE TITLE
Update tooling and dependencies

### ISSUE THREAD

**Issue by guyellis** [guyellis/learn#789]
The tooling and dependencies have atrophied and are out-of-date. This is causing Greenkeeper PRs to fail the build and as such I've just been deleting these PRs and branches without merging them which is why the dependencies are so out-of-date.

We need to update the tools and dependencies and get the build working again before working on new features. This should be too difficult a task.

**Comment by mateusmarquezini** [comment]
Hi Guy! Let me try this. Could you please assign me? Thanks
