### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by guyellis** [guyellis/learn#801]
At 7/19/19 the outdated dependencies are:

```
Package                  Current   Wanted   Latest  Location
babel-eslint              10.0.1   10.0.1   10.0.2  learn
babel-jest                23.6.0   23.6.0   24.8.0  learn
babel-loader               7.1.5    7.1.5    8.0.6  learn
css-loader                 2.1.1    2.1.1    3.1.0  learn
eslint-plugin-jest       22.11.0  22.11.0  22.11.1  learn
eslint-plugin-jsx-a11y     6.2.2    6.2.2    6.2.3  learn
eslint-plugin-react       7.14.1   7.14.1   7.14.2  learn
jest                      23.6.0   23.6.0   24.8.0  learn
mini-css-extract-plugin    0.7.0    0.7.0    0.8.0  learn
moment                    2.22.2   2.22.2   2.24.0  learn
node-sass                 4.11.0   4.11.0   4.12.0  learn
prop-types                15.7.1   15.7.1   15.7.2  learn
webpack                   4.35.3   4.35.3   4.36.1  learn
webpack-dashboard          3.0.3    3.0.3    3.0.7  learn
```

These need to be updated. Some of these can be updated en masse and other will need to be done one-by-one. Issue for [css-loader is here](#802)

**Comment by mateusmarquezini** [comment]
I've updated some libraries such as eslint, jest, css-loader and everything was working fine, but when I did an updated for babel libs the test build stopped working with too many syntax problems :disappointed:

**Comment by guyellis** [comment]
@mateusmarquezini What do you think of doing smaller updates? So just updating one or two dependencies at a time and then tackling the more troublesome updates at the end?

**Comment by guyellis** [comment]
@mateusmarquezini - I'm wondering if switching from Babel to Typescript would solve this problem. I haven't actually tried this yet on any project but these are my thoughts.

Babel transpiles from es-future syntax to a more broadly supported version of JS.

Typescript transpiles from Typescript syntax to a broadly supported version of JS or whatever version you tell it to transpile to. But Typescript will also support transpiling from .js and .jsx files if the config is correctly set. So I think that it can be a replacement for Babel and might be easier to support going forward. It would also mean that we could use `.ts` and `.tsx` files and syntax in some places if we wanted.

WDYT?

**Comment by guyellis** [comment]
@mateusmarquezini looks like it's a pretty easy change. Here's an article that describes it. Let me know if you want to do this? If not I can do it but I don't want to duplicate something that you're already doing. https://medium.com/pleo/migrating-a-babel-project-to-typescript-af6cd0b451f4

**Comment by guyellis** [comment]
For the Babel to Typescript change I just created #820 so that it's a separate issue and I assigned it to you @mateusmarquezini - however if you don't have time for this just assign it to me and I'll do it. It looks like fun.

We can use this issue to update the other dependencies.

**Comment by mateusmarquezini** [comment]
Hey @guyellis, nice! Tomorrow morning I'll try to make these changes and I keep you updated, Ok? But yes, I think it's a good idea and we can try migrating from Babel to Typescript.

**Comment by mateusmarquezini** [comment]
Hey @guyellis,
I've changed from Babel to Typescript as you can see in the latest commit, but I just saw that the CI gave an error while it was running the tests.
After that, I removed the .babelrc file because I've changed from Babel to Typescript. 
Well, I'm getting 2 problems now:

- When I run the test build or anything that executes the test build, it breaks with too many syntax errors (I think this is a problem with localStorage settings too.)
I pasted a part of the log here: https://pastebin.com/fqn5XRxW

- Also, after migrating to Typescript to transpile our js and jsx files the application doesn't load anymore. I can see only the white screen with the `Loading...` text.

Could you please help me? It will be very appreciated. I'm working on branch **issue_801**

Thanks!

**Comment by mateusmarquezini** [comment]
@guyellis you can ignore the Travis errors because I've removed the .babelrc file as I said so, these errors involving babel-core aren't happening anymore.

**Comment by guyellis** [comment]
I think that this might be happening because Jest doesn't know how to load the `...test.jsx` files because they haven't been transpiled.

Usually these test files are named `...test.tsx` and not `...jsx` (but we don't want to do that - yet)

The entry in jest.config.js that helps with that is:

```javascript
  transform: {
    '.+\\.tsx?$': 'ts-jest',
  },
```

and you also have to `npm i --save-dev ts-jest`

For us I'm guessing that we would do something like this in the jest.config.js:

```javascript
  transform: {
    '.+\\.(t|j)sx?$': 'ts-jest',
  },
```

Which would allow all JS and TS files to go through that transform before testing.

I haven't tried any of this yet.

I'm on Pacific time and it's morning here. I hope to be able to circle back to this and look at it again in the evening. Let me know if you get a chance to try that idea above and how it works.

**Comment by mateusmarquezini** [comment]
Hi @guyellis, thanks! I have tried this but it still isn't working 😞.

What you said make sense, but doing these steps it keeps giving the same errors.

I can't commit my changes because, before commit, the test build runs and it fails.

Let me know if you find any solution. Anyway, I'm going back to work on it during the week.

**Comment by guyellis** [comment]
@mateusmarquezini - my apologies - I got really busy and not able to look right this minute. Hope to get a bit more time later in the week.

You can disable the precommit hook with the `n` flag. So when you commit you would do:

```shell
git commit -nm'commit message'
```

**Comment by guyellis** [comment]
@mateusmarquezini - my apologies for taking so long on this. I've added a bunch of iterative commits on that branch and did a PR against master. I think that it's fixed. It was a bunch of other co-dependencies that needed to be updated.

**Comment by mateusmarquezini** [comment]
hi @guyellis ! Good work! I'm going to pull these changes in my local branch and see them.
