### ISSUE TITLE
Update dependency css-loader

### ISSUE THREAD

**Issue by guyellis** [guyellis/learn#802]
Update dependency `css-loader` to latest version.

**Comment by mateusmarquezini** [comment]
Hi @guyellis , 

As you created a new issue to update many other dependencies, I think this issue may be closed, right?
Anyway, I'm going to update **css-loader** in other issue too.

**Comment by guyellis** [comment]
Because this wasn't just a simple change-the-version-number of the dependency I split it out into its own issue to isolate it and make it easier to upgrade. However that's fine if it gets updated along with the other issue.

**Comment by mateusmarquezini** [comment]
Ok @guyellis ! No problem!

**Comment by guyellis** [comment]
Thanks for fixing this @mateusmarquezini 

Tip: If you include `Fixes #802` in the PR request title/subject then when the PR is merged it will automatically close the issue.
